## library() calls go here
library(conflicted)
library(dotenv)
library(drake)
library(rmarkdown)
library(tidyverse)
library(knitr)
library(drake)
library(colorspace)
library(magick)
library(ggspectra)
library(scales)
library(photobiology)
library(photobiologyWavebands)

conflicted::conflict_prefer("pull", "dplyr")
conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")
